### ISSUE TITLE
Bugs that cause logcat errors and even app crashes

### ISSUE THREAD

**Issue by Srrsrr123** [majestyhao/com.hectorone.multismssender_13_src#1]
**_Describe the bug_**

Dear developer!  In the process of using it, I found four bugs causing logcat errors and even app crashes. As shown in the figure, when pressing the button, the logcat errors occurs or the app crashes. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.

**_Screenshots_**

1、
![4Z UQNMGMMUWQKNGRP8 FKQ](https://user-images.githubusercontent.com/79861356/222471547-5e433d09-2cbd-4753-bb22-2a724aa7209f.png)

![HPVV @6GF)JSM2M41}N}YFD](https://user-images.githubusercontent.com/79861356/222471574-127fb999-1f76-45e1-9b91-77bef643da68.png)

2、
![P`CZSCXDXN{9EEB2~$ SBJK](https://user-images.githubusercontent.com/79861356/222471740-95159832-97d4-4e1f-9249-664e2bb1ff77.png)

![V72CK4X9{MLS6MW6D2LW0L9](https://user-images.githubusercontent.com/79861356/222471765-bdd4abec-6241-47a3-84d9-0ec269ad10fa.png)

3、
![0OM_{LW@WU_H N%GP_6~8_N](https://user-images.githubusercontent.com/79861356/222471817-382ac340-9929-46ab-9dad-6d6f6cf4a32c.png)

![K0 D Q( F(RN8 {53SG2VR4](https://user-images.githubusercontent.com/79861356/222471842-1614d340-952e-4de1-8360-6b05118f7db8.png)

4、
![D5BGX)OR)(SX C%YP6@O_~G](https://user-images.githubusercontent.com/79861356/222471889-da855517-2a04-42f6-a33b-10149040559e.png)

![O(`)3N)}`G$2~}U_OBM74XV](https://user-images.githubusercontent.com/79861356/222471915-396ab26c-8721-4a50-99bc-4a26329f278f.png)

**Comment by Srrsrr123** [comment]
If you see my question, I sincerely hope to get an answer, even if it is a simple answer. This is very helpful for me.

**Comment by majestyhao** [comment]
It's just a clone from https://gitlab.mathux.org/Mathieu/MultiSmsSender, better ask there. It's quite old btw, not recommended to rebase on it.

**Comment by Srrsrr123** [comment]
> It's just a clone from https://gitlab.mathux.org/Mathieu/MultiSmsSender, better ask there. It's quite old btw, not recommended to rebase on it.

I'm glad you took time out of your busy schedule to reply. I would appreciate it if you could help confirm that these are bugs.
